membersrvc:
  container_name: membersrvc
  image: hyperledger/fabric-membersrvc
  volumes:
    - ./membersrvc:/user/membersrvc
  # copy netvote memberservice yaml with hardcoded admin credentials (for dev)
  command: sh -c "cp /user/membersrvc/* /opt/gopath/src/github.com/hyperledger/fabric/membersrvc/ && membersrvc"
  ports:
    - 7054:7054

peer:
  container_name: peer
  image: hyperledger/fabric-peer
  environment:
    - CORE_PEER_ADDRESSAUTODETECT=true
    - CORE_VM_ENDPOINT=unix:///var/run/docker.sock
    - CORE_LOGGING_LEVEL=DEBUG
    - CORE_PEER_ID=vp0
    - CORE_SECURITY_ENABLED=true
    - CORE_PEER_PKI_ECA_PADDR=membersrvc:7054
    - CORE_PEER_PKI_TCA_PADDR=membersrvc:7054
    - CORE_PEER_PKI_TLSCA_PADDR=membersrvc:7054
    - CORE_PEER_VALIDATOR_CONSENSUS_PLUGIN=noops
  # this gives access to the docker host daemon to deploy chain code in network mode
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
  # have the peer wait 10 sec for membersrvc to start
  #  the following is to run the peer in Developer mode - also set sample DEPLOY_MODE=dev
  command: sh -c "sleep 10; peer node start --peer-chaincodedev"
  #command: sh -c "sleep 10; peer node start"
  ports:
    - 7051:7051
    - 7050:7050
    - 7053:7053
  links:
    - membersrvc

netvote:
  container_name: netvote
  image: hyperledger/fabric-starter-kit
  volumes:
    # mount local dev into container
    - ./node/:/user/vote
    - ./go/:/opt/gopath/src/netvote/go/
  environment:
    - MEMBERSRVC_ADDRESS=membersrvc:7054
    - PEER_ADDRESS=peer:7051
    - KEY_VALUE_STORE=/tmp/hl_sdk_node_key_value_store
    - DEPLOY_MODE=dev
    - DEPLOY_USER=deployer
    - DEPLOY_PASS=netvotedeployer
    - ADMIN_USER=admin
    - ADMIN_PASS=netvoteadmin
    - CORE_CHAINCODE_ID_NAME=netvote
    - CORE_PEER_ADDRESS=peer:7051
  # deploy
  command: sh -c "sleep 20; /opt/gopath/src/netvote/go/chaincode/chaincode"
  stdin_open: true
  tty: true
  links:
    - membersrvc
    - peer
